spring:
  application:
    name: plan-stock-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: project.demo.plan_stock_service.kafkaConsumer.OrderEvent
        spring.json.use.type.headers: false
      enable-auto-commit: true
      auto-commit-interval: 1000
    topic:
      name: order-topic-2

server:
  port: 8082
